### ISSUE TITLE
Add YouTube resources for web development.

### ISSUE THREAD

**Issue by AnuragSharma122** [DhanushNehru/Ultimate-Web-Development-Resources#57] opened 2022-10-15 14:55 UTC
Please assign this issue to me.
Also, add hactoberfest label to this issue.

**Comment by SattyamSamania** [comment] 2022-10-19 12:17
Hey @DhanushNehru if the issue is still open can I work on this under Hacktoberfest contribution?

**Comment by Mansi782** [comment] 2023-10-08 05:37
please assign this issue to me i would like to work on this

**Comment by Mansi782** [comment] 2023-10-08 05:37
please assign this issue to me i would like to work on this

**Comment by anushka9555** [comment] 2023-10-15 21:38
Hello @DhanushNehru can I work on this issue?

**Closed** 2023-10-16 15:04 UTC
Labels: hacktoberfest
